version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: deploy/remove_root_dir.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root
    - location: deploy/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy/stop_server.sh
      timeout: 300
      runas: root
