version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli@17.0.0
  build:
    commands:
      - npm run build:ci
  post_build:
    commands:
      - aws s3 sync dist/frontend/ s3://aws-pipeline-test-angular --delete
artifacts:
  files:
    - '**/*'
  name: BuildArti
