version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci
artifacts:
  files:
    - '**/*'
  base-directory: base_location
  name: aws-test-pipeline-build-artifact
  discard-paths: no
